spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      name: edison
      password: 123456
  jmx:
    default-domain: config-center
server:
  port: 8888
  servlet:
    context-path: /

